function [composition_matrix, material_matrix] = ...
        create_material_grid_sphere(filename_input, ...
        radius_list, x_center_list, ...
        refractive_index_list)
    
    [x_grid, y_grid, z_grid] = fdtd_bounds(filename_input);

    if numel(y_grid) < 2
        [x_ndgrid, z_ndgrid] = ndgrid(x_grid, z_grid);
        composition_matrix = create_composition_matrix_cylinders( ...
            x_ndgrid, z_ndgrid, ...
            radius_list, x_center_list);
    else
        [x_ndgrid, y_ndgrid, z_ndgrid] = ndgrid(x_grid, y_grid, z_grid);

        composition_matrix = create_composition_matrix_spheres( ...
            x_ndgrid, y_ndgrid, z_ndgrid, ...
            radius_list, x_center_list);
    end

    material_matrix = create_material_matrix( ...
        radius_list, x_center_list, ...
        refractive_index_list);
end
